name: Setup x-ui with ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-x-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip jq

      - name: Download and Run x-ui Install Script
        run: |
          apt-get install -y tmate openssh-client

      - name: Start x-ui Service
        run: |
          tmate -F

     
