name: Setup x-ui with ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-x-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip

      - name: Download and Run x-ui Install Script
        run: |
          curl -Ls -o install.sh https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh
          sudo bash install.sh

      - name: Configure x-ui
        run: |
          # Replace these values with desired x-ui credentials and port
          USERNAME="Sachith"
          PASSWORD="s60110777"
          PORT="2020"  # Replace with desired x-ui panel port

          # Apply the configuration for x-ui
          sudo /usr/local/x-ui/x-ui setting -username "$USERNAME" -password "$PASSWORD" -port "$PORT"

      - name: Download ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin/

      - name: Start ngrok for x-ui Port Forwarding
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}  # Set your ngrok authtoken in GitHub Secrets
        run: |
          # Authenticate with ngrok
          ngrok authtoken $NGROK_TOKEN

          # Start ngrok to expose the x-ui panel on port 2020
          nohup ngrok tcp 2020 &

      - name: Display ngrok URL
        run: |
          sleep 5  # Wait for ngrok to initialize
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
