name: Setup x-ui with ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-x-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: create user
        run: |
        #  sudo useradd -m -s /bin/bash -p $(openssl passwd -1 '60110777') root

      - name: Start tmate Service
        run: |
          sudo apt install -y tmate

      - name: start tmate
        run: |
           tmate -F


     
